# Optional: render blueprint for services
services:
  - type: web
    name: helwan-backend
    repo: https://github.com/YOUR_USERNAME/helwan-smart-campus
    env: node
    buildCommand: npm install
    startCommand: npm start
    root: backend
  - type: static
    name: helwan-frontend
    repo: https://github.com/YOUR_USERNAME/helwan-smart-campus
    root: frontend
    buildCommand: npm run build
    publishPath: dist