
version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm run dev
    ports:
      - '4000:4000'
    depends_on:
      - mongo
volumes:
  mongo-data:
