[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[start]
command = "npm start"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
NODE_VERSION = "18"
