[build]
builder = "NIXPACKS"
buildCommand = "npm install"
startCommand = "npm start"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"
